issueOpened: >
  Thank you for reaching out.

  In case you are raising an issue, you can find more information to try to it yourself here:

  - [Wiki & FAQ](https://wiki.safing.io/)
  - [GitHub Issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Asafing+sort%3Aupdated-desc)
  - [Ask on Discord](https://discord.gg/safing)

  Additionally, there is a __ChatGPT-like support bot__ trained on our documentation, that you can [ask for help in this Discord channel](https://discord.com/channels/389815143711637517/1106170808704974878).

  Please keep in mind that the free version of Portmaster only has community support and inactive issues are automatically closed after a while.
  If you find our work brings value to you, please consider supporting it by purchasing Supporter or Unlimited Packages https://safing.io/pricing/.

  If you are a customer, first of all: Thank You!
  If you want to claim priority support for this issue, please send us a message [on Discord](https://discord.gg/safing) or [via Email](mailto:support@safing.io) with your username and the link to this issue, so we can prioritize accordingly.


pullRequestOpened: >
  Thank you for your pull request.

  If you have not already, please read our [contribution guideline](https://wiki.safing.io/en/Contribute).
  If this change is bigger and you have not discussed it with us, please head over to [Discord](https://discord.gg/safing) to discuss your idea.
