name: Go

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.49.0
        only-new-issues: true
        args: -c ./.golangci.yml --timeout 15m

    - name: Get dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: ./test --test-only
