# This workflow warns and then closes stale issues and PRs.
# Docs: https://github.com/actions/stale
name: Close Stale Issues 

on:
  schedule:
    - cron: "17 5 * * 1-5" # run at 5:17 (UTC) on Monday to Friday

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Handle stale issues
          stale-issue-label: 'stale'
          # Exemptions
          exempt-issue-assignees: 'dhaavi,Raphty'
          exempt-issue-labels: 'support,faq,dependencies,pinned,security'
          # Mark as stale
          days-before-issue-stale: 63 # 2 months / 9 weeks
          stale-issue-message: |
            This issue has been automatically marked as inactive because it has not had activity in the past two months.
            
            If no further activity occurs, this issue will be automatically closed in one week in order to increase our focus on active topics.
          # Close
          days-before-issue-close: 7 # 1 week
          close-issue-message: |
            This issue has been automatically closed because it has not had recent activity. Thank you for your contributions.

            If the issue has not been resolved, you can find more information or continue the conversation here:

            - [Wiki & FAQ](https://wiki.safing.io/)
            - [Get Help on Discord](https://discord.gg/safing)

            Please keep in mind that the free version of Portmaster only has limited support. If you find our work brings value to you, please consider supporting it by purchasing Portmaster Plus or Pro: https://safing.io/pricing/.

            If you already are a paying subscriber and want this issue to be checked out by Safing, please send us a message [on Discord](https://discord.gg/safing) or [via Email](mailto:support@safing.io) with your username and the link to this issue, so we can prioritize accordingly.
          # TODO: Handle stale PRs
